first half of sellerX case study
reflex-dev/reflex-web pull request #1052
Opened 2024-10-25 16:50 UTC by tgberkeley

2024-10-28 16:12 UTC, tgberkeley commented
Only relevant file to review here is the SellerX case study file in the case-studies folder

2024-10-31 02:25 UTC, Alek99 requested changes

2024-10-31 02:25 UTC, Alek99 commented on case-studies/sellerx.md
> +Mike and his team initially started with [Streamlit](https://streamlit.io), a python framework to build simple web apps, but it was very limited. Their first concern was with the inefficiencies of th
Instead of limited lets be more descriptive

2024-12-06 23:58 UTC, tgberkeley commented
Moved to a new PR

2024-12-06 23:58 UTC, closed without merging