Tom alek/graphing docs
reflex-dev/reflex-web pull request #234
Opened 2023-10-03 17:51 UTC by Alek99

2023-10-03 20:31 UTC, masenf commented
I can't seem to run it...

```console
  File "/Users/masenf/code/reflex-dev/reflex/reflex/reflex.py", line 146, in run
    prerequisites.get_app()
  File "/Users/masenf/code/reflex-dev/reflex/reflex/utils/prerequisites.py", line 114, in get_app
    app = __import__(module, fromlist=(constants.APP_VAR,))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/masenf/code/reflex-dev/reflex-web/pcweb/pcweb.py", line 6, in <module>
    from pcweb.component_list import component_list
  File "/Users/masenf/code/reflex-dev/reflex-web/pcweb/component_list.py", line 191, in <module>
    [rx.GraphingTooltip],
     ^^^^^^^^^^^^^^^^^^
AttributeError: module 'reflex' has no attribute 'GraphingTooltip'. Did you mean: 'graph_tooltip'?
```

2023-10-03 21:00 UTC, masenf requested changes
partial review, still going through

2023-10-03 21:00 UTC, masenf commented on docs/library/graphing/brush.md
> +                rx.brush(data_key="name", height=30, stroke="#8884d8"),
is the brush for scaling the data axes?

2023-10-03 22:40 UTC, Alek99 commented
This is not the final docs just keep that in mind I wanted to merge something in because I didn't want the pr to get too big

2023-10-03 22:40 UTC, Alek99 commented
I'll be adding follow ups to this

2023-10-04 00:31 UTC, tgberkeley commented
Points to change:

can't add list … to funnel chart 

ordering of x axis on scatter chart

error bars taking in lists and integers, and x axis ones not rendering

what is reference line and how do we rename this component in the sidebar as here there are 3 components in one

change the XAxis title to x, y , z axes or something

2023-10-04 04:36 UTC, Alek99 commented
Ok addressing these comment rn will push a follow up tonight

2023-10-04 06:52 UTC, Alek99 commented
I've solved everything on that list except error bat made an issue on rechart because I believe it may be a bug https://github.com/recharts/recharts/issues/3811

2023-10-04 21:05 UTC, tgberkeley approved these changes

2023-10-04 21:07 UTC, merged