Gallery-page-fixed
reflex-dev/reflex-web pull request #298
Opened 2023-11-03 03:26 UTC by kisharnath

Gallery page not found fixed

2023-11-06 19:52 UTC, picklelo requested changes
Thanks for fixing - can you update the `.gitignore` changes?

2023-11-06 19:52 UTC, picklelo commented on .gitignore
> -**/*.db
Can you undo the changes to this file?

2023-11-06 23:57 UTC, kisharnath commented on .gitignore
> -**/*.db
I have updated the file .

2024-03-25 23:53 UTC, picklelo commented
This change made it in in another PR

2024-03-25 23:53 UTC, closed without merging