docs: Improves README.md file
reflex-dev/reflex-web pull request #305
Opened 2023-11-12 09:10 UTC by ankur0904

This pull request introduces enhancements to the `README.md` file for the reflex-web repository-
- provide how to setup the project locally,
- provide comprehensive and clear instructions for setting up the project with required `commands`
- visual improvements have been made to the README
- addition of badges.

**Question**
- Can I add `reflex` [logo](https://github.com/reflex-dev/reflex-web/blob/main/assets/Reflex.svg) to the `README.md` ?

2023-11-14 21:14 UTC, picklelo requested changes
Thanks for adding this, just a couple comments

2023-11-14 21:14 UTC, picklelo commented on README.md
> +- It's built with [Reflex](https://reflex.dev/), a Python web framework.
instead of "a Python web framework" can we make it "a framework to build web apps in pure Python"

2023-11-14 21:14 UTC, picklelo commented on README.md
> +Reflex.dev is a groundbreaking web development framework that empowers Python developers to seamlessly create web apps without the nuances of traditional frontend tools. Its open-source core framewor
For the first sentence I think we don't need to say "groundbreaking" let's just make it something like "Reflex is a full-stack web framework that allows developers to build their app in pure Python, and deploy with a single command".

2023-11-16 09:46 UTC, ankur0904 commented
@picklelo Made the suggested changes.

2023-11-16 18:50 UTC, picklelo approved these changes
looks good, thanks for adding!

2023-11-16 18:50 UTC, merged