Checkbox+Button
reflex-dev/reflex-web pull request #356
Opened 2024-01-10 00:07 UTC by Alek99

2024-01-10 00:40 UTC, masenf requested changes
we should avoid the chakra hstack and vstack components in the new docs.

2024-01-10 00:40 UTC, masenf commented on docs/library/forms/button.md
> +The `disabled` prop disables the button, by default it is `False`.
```suggestion
The `disabled` prop disables the button, by default it is `False`. A disabled button does not respond to user interactions such as click and cannot be focused.
```

2024-01-10 00:40 UTC, masenf commented on docs/library/forms/button.md
> +    return rx.hstack(
we should use the radix flex with `justify="between"`

2024-01-10 00:40 UTC, masenf commented on docs/library/forms/button.md
> +        rx.heading(
```suggestion
        rdxt.heading(
```

2024-01-10 00:40 UTC, masenf commented on docs/library/forms/checkbox.md
> +The `on_change` trigger is called when the checkbox is clicked.
```suggestion
The `on_checked_change` trigger is called when the checkbox is clicked.
```

2024-01-10 00:40 UTC, masenf commented on docs/library/forms/checkbox.md
> +The `color` prop changes the color of the checkbox. The default color is `primary`.
```suggestion
### Color Scheme

The `color_scheme` prop changes the color of the checkbox. The default color maps to the `accent_color` in the app's `theme`.
```

2024-01-10 00:40 UTC, masenf commented on docs/library/forms/checkbox.md
> +The `size` prop changes the size of the button. The default size is `2`.
```suggestion
The `size` prop changes the size of the checkbox. The default size is `2`.
```

2024-01-15 19:43 UTC, picklelo commented on pcweb/pcweb.py
> +for key in chakra_components:
Shouldn't need the changes in this file

2024-01-16 05:59 UTC, closed without merging