rx.match docs
reflex-dev/reflex-web pull request #372
Opened 2024-01-16 14:58 UTC by ElijahAhianyo

2024-01-16 19:49 UTC, Alek99 requested changes

2024-01-16 19:49 UTC, Alek99 commented on docs/library/layout/match.md
> +
Extra spaces

2024-01-16 19:49 UTC, Alek99 commented on docs/library/layout/match.md
> +        ),
Should use the radix select, variant soft should shown the color better

2024-01-16 19:49 UTC, Alek99 commented on docs/library/layout/match.md
> +        rx.select(
Radix select

2024-01-16 19:49 UTC, Alek99 commented on docs/library/layout/match.md
> +            rx.button("decrement", on_click=MatchMultiPropState.decr),
switch order of these increment on right and decrement left

2024-01-16 19:49 UTC, Alek99 commented on docs/library/layout/match.md
> +            color= rx.match(
A little hard to tell the color is changing maybe make it more apparent somehow, possible change a background color instead

2024-01-18 21:00 UTC, Alek99 requested changes

2024-01-18 22:18 UTC, ElijahAhianyo commented on docs/library/layout/match.md
> +
I think the bg color comes from the `md` block? Im not sure how to change that

2024-01-18 22:20 UTC, ElijahAhianyo commented on docs/library/layout/match.md
> +            background_color= rx.match(
what does this comment refer to?

2024-01-19 05:57 UTC, Alek99 commented on docs/library/layout/match.md
> +
Then we need to separate it

2024-01-19 05:58 UTC, Alek99 commented on docs/library/layout/match.md
> +            background_color= rx.match(
> what does this comment refer to?

https://github.com/reflex-dev/reflex-web/pull/372#discussion_r1457971363

2024-01-21 23:09 UTC, picklelo approved these changes

2024-01-24 20:18 UTC, merged