fix links to use hyphen
reflex-dev/reflex-web pull request #517
Opened 2024-03-05 23:07 UTC by Lendemor

2024-03-05 23:27 UTC, picklelo commented on pcweb/pages/docs/__init__.py
> +t = True
leftover?

2024-03-06 00:03 UTC, picklelo requested changes
Actually I think the move here is to modify the `.md` file names to always use `-` - so there's consistency between the names and the url. Then maybe we just add an assert here that it doesn't contain an underscore

2024-03-06 19:14 UTC, picklelo reviewed
Looks good, I think we just have to modify how we do the dynamic name spacing now (convert to snake_case before setting it in the namespace)

2024-03-06 19:38 UTC, Lendemor commented
> Looks good, I think we just have to modify how we do the dynamic name spacing now (convert to snake_case before setting it in the namespace)

Investigating why but they are already snake_cased in the namespace, yet it still fail.

2024-03-12 01:00 UTC, picklelo approved these changes

2024-03-12 01:01 UTC, merged