Improve Event Docs Section
reflex-dev/reflex-web pull request #663
Opened 2024-04-24 19:33 UTC by Alek99

2024-04-25 00:53 UTC, masenf requested changes

2024-04-25 00:53 UTC, masenf commented on docs/events/page_load_events.md
> +Another example would be checking if the user is authenticated when the page loads. If the user is not authenticated, we redirect them to the login page. If they are authenticated, we redirect don't
```suggestion
Another example would be checking if the user is authenticated when the page loads. If the user is not authenticated, we redirect them to the login page. If they are authenticated, we don't do anything, letting them access the page. This `on_load` event would be placed on every page that requires authentication to access.
```

2024-04-25 00:53 UTC, masenf commented on docs/events/yield_events.md
> +This example below shows how to yield a 100 updates to the UI.
```suggestion
This example below shows how to yield 100 updates to the UI.
```

2024-04-25 00:53 UTC, masenf commented on docs/events/yield_events.md
> +
```suggestion
```md alert
# Reference other Event Handler via class

When chaining another event handler with `yield`, access it via the state class, not `self`.
```
```

2024-04-25 00:53 UTC, masenf commented on docs/events/event_arguments.md
> +    colors: list[str] = ["rgba(245,168,152)", "MediumSeaGreen", "#DEADE3"]
viva la france 🇫🇷

2024-05-24 23:58 UTC, masenf approved these changes
we should bring this

2024-05-28 20:50 UTC, picklelo commented on docs/events/yield_events.md
> +            _hover={"cursor": "pointer"},
Needs a double curly brace to escape - I'm going to update flexdown to not catch these as it comes up too much.

2024-05-28 22:08 UTC, picklelo approved these changes
lgtm

2024-05-28 22:18 UTC, merged