update recipe docs
reflex-dev/reflex-web pull request #723
Opened 2024-05-23 16:33 UTC by carlosabadia

2024-05-23 18:11 UTC, Alek99 requested changes
Nice the component looks great. For all the code blocks the helper functions should come first above, the main function they are referenced in.

2024-05-23 19:21 UTC, HongyuHansonYao commented on docs/recipes/auth/login_form.md
> +## Login card with third-party auth provider
Long titles sometime spills, also consider simplify the titles. We don't need navbar in name of every variants. 
![Screenshot 2024-05-23 at 12 17 44](https://github.com/reflex-dev/reflex-web/assets/159659100/09a4cdc2-4d88-4d95-950f-9ff78a86cfd2)
![Screenshot 2024-05-23 at 12 18 19](https://github.com/reflex-dev/reflex-web/assets/159659100/77a1bccb-43ae-4a8c-9530-f12c96d46b5a)

2024-05-24 19:27 UTC, HongyuHansonYao approved these changes

2024-05-27 18:10 UTC, carlosabadia commented
All the new changes are also in Alek's branch with this new PR https://github.com/reflex-dev/reflex-web/pull/733

2024-05-28 18:06 UTC, closed without merging